package com.alanpatrik.sghss.api.comum;

public interface Constantes {
    /*
    * Mensagens
    * */
    String OK_MESSAGE = "SUCCESS";
    String NO_CONTENT_MESSAGE = "SUCCESS";
    String CREATE_MESSAGE = "SUCCESS";
    String ERRO_MESSAGE = "ERROR";
    String BAD_REQUEST_MESSAGE = "Paramêtro(s) de entrada inválido(s).";
    String NOT_FOUND_MESSAGE = "Registro não encontrado.";
    String CONFLICT_MESSAGE = "Registro já possui cadastro.";

    /**
     * Roles
     * */
    String LOGON_ROLE_SUPORTE_SISTEMA = "SGHSS.SUPPORT.SISTEMA";
    String LOGON_ROLE_ADMIN_SISTEMA = "SGHSS.ADMIN.SISTEMA";
    String LOGON_ROLE_ADMIN_CLINICA = "SGHSS.ADMIN.CLINICA";
    String LOGON_ROLE_TELEMEDICINA = "SGHSS.TELEMEDICINA";
    String LOGON_ROLE_ENFERMEIRO = "SGHSS.ENFERMEIRO";
    String LOGON_ROLE_PACIENTE = "SGHSS.PACIENTE";
    String LOGON_ROLE_TECNICO = "SGHSS.TECNICO";
    String LOGON_ROLE_MEDICO = "SGHSS.MEDICO";

    /**
     * Privilégios
     * */
    String PRIV_VISUALIZAR_HISTORICO = "SGHSS.VISUALIZAR_HISTORICO";
    String PRIV_ATUALIZAR_PRONTUARIO = "SGHSS.ATUALIZAR_PRONTUARIO";
    String PRIV_RECEBER_NOTIFICACOES = "SGHSS.RECEBER_NOTIFICACOES";
    String PRIV_ACESSAR_TELECONSULTA = "SGHSS.ACESSAR_TELECONSULTA";
    String PRIV_GERENCIAR_CADASTROS = "SGHSS.GERENCIAR_CADASTROS";
    String PRIV_GERENCIAR_SEGURANCA = "SGHSS.GERENCIAR_SEGURANCA";
    String PRIV_CONTROLAR_INTER = "SGHSS.CONTROLAR_INTERNACOES";
    String PRIV_CADASTRAR_PACIENTE = "SGHSS.CADASTRAR_PACIENTE";
    String PRIV_GERENCIAR_AGENDAS = "SGHSS.GERENCIAR_AGENDAS";
    String PRIV_AGENDAR_CONSULTA = "SGHSS.AGENDAR_CONSULTA";
    String PRIV_GERAR_RELATORIOS = "SGHSS.GERAR_RELATORIOS";
    String PRIV_EMITIR_RECEITA = "SGHSS.EMITIR_RECEITA";
}
