app.base-url=http://localhost:8080

spring.profiles.active=dev
spring.application.name=sghss-api

# H2-CONSOLE
spring.datasource.url=jdbc:h2:mem:sghssdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# Date formater
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss
spring.jackson.time-zone=America/Sao_Paulo

# EMAIL
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=46e9a4a5673503
spring.mail.password=bffd3b73770626
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.auth.starttls.enable=true
spring.messages.basename=messages
spring.messages.encoding=UTF-8

# remetente padrão
mail.from=noreply@sghss.com

# LOGGER
logging.level.root=INFO
logging.level.com.alanpatrik.sghss.api=DEBUG
logging.file.name=logs/sghss-api.log

# JWT
jwt.secret=ÇOIJEPWKQPWKEFBJHSDFYTFERYUGQWIUEJPODKSDLFNJHDGFTW
jwt.expiration-minutes=60
