spring.profiles.active=dev
spring.application.name=sghss-api

# H2-CONSOLE
spring.datasource.url=jdbc:h2:mem:sghssdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# LOGGER
logging.level.root=INFO
logging.level.com.alanpatrik.sghss.api=DEBUG
logging.file.name=logs/sghss-api.log

# JWT
jwt.secret=ÇOIJEPWKQPWKEFBJHSDFYTFERYUGQWIUEJPODKSDLFNJHDGFTW
jwt.expiration-minutes=60

